### PR TITLE
Added Javadoc comments to Player (were missing)

### PR DESCRIPTION
**Pull request by baldurp12**
Comments missing in last pull request, fixed now.

### CODE REVIEW

**Comment by Njallzzz** [comment]
I have looked at the code. This is fine, I will reopen the pull request.

**Review by ludvikkemp — COMMENTED** [review]
flottur grunnur

**Comment by ivarmarkusson** [comment]
Simple and stylish, I like it!

**Review by Njallzzz — APPROVED** [review]
I'll merge this then.

**Pull request merged**
